<script lang="ts">
	import { page } from '$app/stores';
	import { getStory } from '$lib';
	import { ArrowUp, Clock, Loader, LogIn } from 'lucide-svelte';
	import { onMount } from 'svelte';
	import Time from 'svelte-time/Time.svelte';
	import StoryList from '$lib/story.svelte';
	import Comment from '$lib/comment.svelte';

	let id = $page.params.id,
		user;

	let stories: Array<Story> = [];
	let comments = [];

	type Story = {
		by: string;
		descendants: number;
		id: number;
		kids: Array<number>;
		score: number;
		time: number;
		title: string;
		type: string;
		url: string;
	};

	onMount(async () => {
		const baseURL = 'https://hacker-news.firebaseio.com/v0/user/';
		const url = baseURL + id + '.json';

		const response = await fetch(url);
		const data = await response.json();
		user = data;

		for (const id of user.submitted) {
			const story = await getStory(id);

			console.log(story.type);
			if (story.type == 'story') {
				stories = [...stories, story];
			} else if (story.type == 'comment') {
				comments = [...comments, story];
			} else {
				console.log('SUBMITTED NOT OF TYPE STORY OR COMMENT!!!');
			}
		}

		console.log(stories);
		console.log(comments);
	});
</script>

<div class="prose prose-invert mx-auto">
	<h1 class="text-center text-3xl sm:text-5xl md:text-6xl">{id}</h1>
	<img
		alt="Autogenerated avatar of a robot."
		src="https://robohash.org/{id}"
		class="mx-auto rounded-full border border-zinc-700 bg-zinc-800/30"
	/>
	<div class="mx-auto w-fit text-2xl">
		{#if user}
			<ArrowUp class="mr-3 inline " />{user?.karma}
		{:else}
			loading...
		{/if}
	</div>
	<br /><br />
	{#if user}
		<Clock class="ml-3 mr-3 inline " />joined <Time timestamp={user.created * 1000} />
		<br /><br />
		{#if user.about}
			{user.about}
		{/if}
		{#if user.submitted.length !== 0}
			<hr />
			<br />
			{#if stories.length !== 0}
				<h2>Stories</h2>
				{#each stories as story}
					<StoryList {story} />
				{/each}
			{/if}
			<br />
			{#if comments.length !== 0}
				<h2>Comments</h2>
				{#each comments as comment}
					<blockquote class="text-zinc-300">
						<Clock class="mr-3 inline" /><Time timestamp={comment.time * 1000} />
						<br />
						<div class="mt-3">
							{comment.text}
						</div>
					</blockquote>
				{/each}
				<br /><br />
			{/if}
		{/if}
	{:else}
		loading...
	{/if}
</div>
